name: Deploy Website
on:
  push:
    branches: [website]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: coursier/cache-action@v6
      - uses: VirtusLab/scala-cli-setup@v0.1.18
        with:
          jvm: "temurin:17"
          apps: sbt
      - name: Publish ${{ github.ref }}
        run: sbt docs/docusaurusPublishGhpages
        env:
          GITHUB_DEPLOY_KEY: ${{ secrets.DOC }}
