name: Deploy Website
on:
  push:
    branches: [website]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - uses: olafurpg/setup-scala@v13
      - name: Publish ${{ github.ref }}
        run: sbt docs/docusaurusPublishGhpages
        env:
          GITHUB_DEPLOY_KEY: ${{ secrets.DOC }}
